name: Scheduled Sync1
on:
  schedule:
    - cron: '0 0 * * *' # 每天北京时间早上 8 点自动同步
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Fork
        uses: tgymnich/fork-sync@v1.6.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main  # 你的分支
          head: main  # 原作者的分支
          owner: luestr # 原作者用户名
